name: record-screenshots

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  record-screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    env:
      BRANCH_PREFIX: _screenshots_
      COMMITTER_NAME: github-actions[bot]
      COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      COMMIT_MESSAGE: screenshots
      MAX_AGE_SECONDS: 600 # TODO: 14 days

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

      - name: Get branch name
        id: branch
        shell: bash
        run: |
          hash=$(git ls-files -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')
          echo "branch=${BRANCH_PREFIX}${hash:0:7}" >> "$GITHUB_OUTPUT"

      - name: Check if branch exists
        id: check-branch
        shell: bash
        env:
          BRANCH: ${{ steps.branch.outputs.branch }}
        run: |
          if git show-ref --verify --quiet "refs/remotes/origin/${BRANCH}"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Record screenshots
        if: ${{ steps.check-branch.outputs.exists == 'false' }}
        run: ./gradlew recordRoborazziDebug

      - name: Upload
        if: ${{ steps.check-branch.outputs.exists == 'false' }}
        uses: daiji256/upload-to-orphan-branch@c7b7f47558b9ebd00985945e85b6a2ff3d0ce883 # v0.1.1
        with:
          branch: ${{ steps.branch.outputs.branch }}
          committer-name: ${{ env.COMMITTER_NAME }}
          committer-email: ${{ env.COMMITTER_EMAIL }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          path: "**/build/outputs/roborazzi"

      - name: Delete outdated screenshots
        run: |
          now=$(date +%s)
          git branch -r --format="%(refname:lstrip=3)" | while read -r branch; do
            if ! [[ "$branch" =~ "$BRANCH_PREFIX"* ]]; then continue; fi

            commit_count=$(git rev-list --count "origin/$branch")
            if [ "$commit_count" -ne 1 ]; then continue; fi

            committer_name=$(git log -1 --format=%an "origin/$branch")
            if [ "$committer_name" != "$COMMITTER_NAME" ]; then continue; fi

            committer_email=$(git log -1 --format=%ae "origin/$branch")
            if [ "$committer_email" != "$COMMITTER_EMAIL" ]; then continue; fi

            commit_message=$(git log -1 --format=%s "origin/$branch")
            if [ "$commit_message" != "$COMMIT_MESSAGE" ]; then continue; fi

            commit_date=$(git log -1 --format=%ct "origin/$branch")
            age=$((now - commit_date))
            if [ "$age" -lt "$MAX_AGE_SECONDS" ]; then continue; fi

            echo "delete $branch"
            git push origin --delete "$branch"
          done
